version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "3000:3000"
  db:
    image: "mysql:latest"
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gin-tutorial
volumes:
  mysql:
    driver: local