version: '3.8'
services:
  api:
    image: "golang:latest"
    ports:
      - 8080:8080
  client:
    image: "node"
    volumes:
      - "./client:/app"
    working_dir: "/app"
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"