version: '3.8'
services:
  api:
    build:
      context: ./docker/server/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server:/app 
    depends_on:
      - db
  client:
    build:
      context: ./docker/client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
    command: bash -c "npm install && npm run dev"
  db:
    image: "mysql:latest"
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gin-tutorial￥
volumes:
  mysql:
    driver: local